version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'echo It Works'

workflows:
  version: 2
  deploy_to_server:
    jobs:
      - deploy