version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 'echo It Works'
      - add_ssh_keys:
          fingerprints:
            - "25:85:79:63:4a:30:05:70:5f:56:5c:b6:2f:93:45:44"
      - run: 'echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts'
      - run: 'rsync -avce ssh . projektmunka@adampapp.ddns.net:/var/www/projektmunka'

workflows:
  version: 2
  deploy_to_server:
    jobs:
      - deploy